[project]
name = "smol-tool-calling-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=0.34.1",
    "pytest>=8.4.1",
    "smolagents>=1.20.0",
]
